version: '3.7'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    # depends_on:
    #   - db
    networks:
      - fvpnetwork

  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - fvpnetwork

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - fvpnetwork

volumes:
  postgres_data:

networks:
  fvpnetwork:
    driver: bridge